image: "node:latest"

stages:
  - test
  - deploy

check types:
  stage: test
  script:
    - npm i -g pnpm
    - pnpm install
    - pnpm run typecheck

run linter:
  stage: test
  script:
    - npm i -g pnpm
    - pnpm install
    - pnpm run lint

deploy gitlab pages:
  stage: deploy
  script:
    - npm i -g pnpm
    - pnpm install
    - pnpm run build
    - mv ./dist ./public
  artifacts:
    paths:
      - public
