image: "node:latest"

before_script:
  - npm i -g pnpm
  - pnpm config set store-dir .pnpm-store
  - pnpm install

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

stages:
  - test
  - deploy

check types:
  stage: test
  script:
    - pnpm run typecheck

run linter:
  stage: test
  script:
    - pnpm run lint

deploy gitlab pages:
  stage: deploy
  script:
    - pnpm run build
    - mv ./dist ./public
  artifacts:
    paths:
      - public
