image: "node:latest"

pages:
    stage: deploy
    script:
        - npm i -g pnpm
        - pnpm install
        - pnpm run build
        - mv ./dist ./public
    artifacts:
        paths:
            - public
